### ISSUE TITLE
Json_Rest_Server não permite id como String ?

### ISSUE THREAD

**Issue by catalunha** [rodrigorahman/json_rest_server#10]
Parabens pelo package RR e equipe.
O JRS realmente não permite id como String ?

**Comment by rodrigorahman** [comment]
@brasizza mestre implementação finalizada, agora o processo existe uma nova tag no config:

idType: int | uuid

Isso faz com que o processo todo seja alterado, enviando agora o id como inteiro ou String dependendo da escolha na configuração. 

Para fazer isso o id virou dynamic em diversos pontos do sistema.

Consegue testar o fluxo do Slack e Websocket pra ver se não vai gerar nenhum problema? 

Obs.: A branch que estou trabalhando está associada aqui na issue

Vlwwww

**Comment by catalunha** [comment]
Parabens. O JRS esta virando uma solução robusta para devs.
