### ISSUE TITLE
Atualização de dado no JSR.

### ISSUE THREAD

**Issue by rodrigorahman** [rodrigorahman/json_rest_server#15]
Atualmente temos uma particularidade no JSR que é: 

Quando executamos qualquer serviço de PUT enviamos o id da tabela para atualização, porém se esse id não existir o JSR está inserindo os dados.

Vocês acham interessante que seja assim? Ou devemos retornar uma exception quando o JSR não encontrar o ID?

Exemplo abaixo:

`http://localhost:8080/products/99999`

Body:
```json
{
    "title": "Academia do flutter"
}
```

**Comment by brasizza** [comment]
Acho que o verbo PUT deve ser exclusivo para atualizar, acho que se não tem id para atualizar pode retornar um 404 de id não encontrado assim como o delete e o PATCH

**Comment by rodrigorahman** [comment]
Alteração realizada, como isso gera uma mudança de comportamento resolvi incrementar para uma release major para evitar qualquer problema: 

Release [v3.0.0](https://github.com/rodrigorahman/json_rest_server/releases/tag/3.0.0).

**Comment by rodrigorahman** [comment]
closed
