### ISSUE TITLE
Inifinit scroll

### ISSUE THREAD

**Issue by welitonsousa** [rodrigorahman/json_rest_server#2]
### Excelente package, parabéns pessoal.
**Queria deixar uma observação:**
É meio complicado fazer paginação sem saber a quantidade de elementos existentes, principalmente quando o app com aqueles infinit scroll, pois do ponto de vista do app, não tem uma forma clara de saber que ele deve parar de carregar a proxima lista

**Comment by rodrigorahman** [comment]
Fala man muito obrigado pela contribuição, vou colocar no nosso roadmap ;-) 

tmj

**Comment by rodrigorahman** [comment]
### Ideia sobre a implementação;

A ideia é o retorno do serviço dessa forma: 

`{
   "total_pages":10,
   "total_value":1000,
   "data":[
      {
         "id":0,
         "nome":"Rodrigo Rahman"
      },
      {
         "id":1,
         "nome":"Rodrigo Rahman"
      }
   ]
}`

Essa feature será adicionado com um **feature toggle** podendo ser habilitada e desabilitada dependendo da necessidade.

Caso alguém tenha algum comentário ou ideia por favor deixe nos comentários

**Comment by catalunha** [comment]
Parabens @rodrigorahman .
Parabens pela contribuição @welitonsousa mas gostaria de fazer uma observação sobre este item. 
**Nao acho necessaria a informação da quantidade total de itens.**
Claro que minha experiencia não é tão grande mas em um database que uso realmente consultar a quantidade total não é necessario para paginação e em outros databases isto poderia ser mais uma consulta.
No meu caso informo uma quantidade de um saldo e depois a quantidade que quero apos este saldo. 
Salto: 0 Quantidade 10 -> Página 1. Retorna primeiros 10 itens. Total da lista 10. Pede proxima página.
Salto: 10*1 Quantidade 10 -> Página 2. Retorna proximos 10 itens. Total da lista 20. Pede proxima página.
Salto: 10*2 Quantidade 10 -> Página 3. Retorna proximos 5 itens. Total da lista 25. Pede proxima página ou se retorno menor que o previsto eu paro.
Salto: 10*3 Quantidade 10 -> Retorna 0 itens, então é fim de paginação.
Assim basta no app eu controlar  a quantidade ja saltos e o limite.
Estou usando o Parse Server (recomendo e aceito comentarios) e a query fica assim:
```
    query.setAmountToSkip((pagination.page - 1) * pagination.limit);
    query.setLimit(pagination.limit);
```
Fica ai minha solução para analise de vcs.

**Comment by munhozfontana** [comment]
Acho que é importante @catalunha, como eu vou saber a quantidade total de elementos nessa situação.
na maioria dos lugares que já trabalhei, trazer a página atual e total de elementos é um padrão de mercado.

![image](https://github.com/rodrigorahman/json_rest_server/assets/29485455/ad5b9797-7f08-475c-9846-6185d68c2322)


muitos frameworks backends trazem como padrão esses valores, um exemplo usando spring boot.
![image](https://github.com/rodrigorahman/json_rest_server/assets/29485455/1b5dd888-7683-4283-9e36-6a0a6c675723)

acredito que total pages é desnecessário, mas o total de itens é fundamental para o melhor aproveitamento da api.

**Comment by catalunha** [comment]
Ok. Obrigado. Caminhando a aprendendo.

**Comment by rodrigorahman** [comment]
> @rodrigorahman , @welitonsousa e @catalunha segue o PR, o que acham?
> 
> #14

@munhozfontana Obrigado pela contruição, vamos analisar o PR ;-)
