### ISSUE TITLE
Problema com a rota auth/refresh

### ISSUE THREAD

**Issue by ViniR-RB** [rodrigorahman/json_rest_server#23]
Enviando tudo de acordo com a documentação porém recebo um 

![image](https://github.com/rodrigorahman/json_rest_server/assets/84464600/227fd52c-e40c-4eec-a9d3-cc3e691bec46)

**Comment by adilsonjuniordev** [comment]
@ViniR-RB , você precisa mandar o token de acesso no header.

**Comment by ViniR-RB** [comment]
Vou enviado no headee de authorization

**Comment by adilsonjuniordev** [comment]
@ViniR-RB  Manda um print do seu header

**Comment by ViniR-RB** [comment]
![image](https://github.com/rodrigorahman/json_rest_server/assets/84464600/2053860d-2868-4ad8-aa7d-a43a725e662d)

**Comment by adilsonjuniordev** [comment]
@rodrigorahman @brasizza 

Fui debugar para encontrar o problema relatado aqui pelo @ViniR-RB , e acho que descobri um bug.

O JWT está sendo gerado com um notBefore recebendo a data atual + validade do token.
Com isso o usuário não consegue fazer um refresh do token antes da expiração do mesmo.

```
notBefore: DateTime.now().add(Duration(seconds: notBefore)),
```
Ao validar o refresh token, está retornando um erro dizendo  que o JWT ainda não é válido:

```"JWT token not yet accepted!"```

Foi implementado dessa maneira de forma proposital, ou é de fato algo que podemos mudar?
Ao meu ver, o usuário deveria poder renovar o seu token a qualquer momento, desde que ele tenha o access_token e o refresh_token.

Se puder fazer essa alteração, eu já faço e subo um novo PR para aprovação.

**Comment by brasizza** [comment]
O fato é evitar que o refresh seja feito sem a necessidade, enquanto o token é válido n tem a necessidade do refresh

**Comment by adilsonjuniordev** [comment]
@brasizza Nesse caso não seria legal a gente colocar um outro status-code diferente de 500?
Poderíamos colocar um outro código ```405``` ou ```406``` com uma mensagem de retorno explicando o motivo que não pode ser renovado. O que vc acha?

**Comment by rodrigorahman** [comment]
@adilsonjuniordev e @brasizza Acredito que o correto seja realmente um 401 Unauthorized com um corpo: 

`{
"error": "refresh_token_not_yet_valid",
"error_description": "The token cannote be used before [data/hora]"
}
`

o que acham?

**Comment by brasizza** [comment]
> @adilsonjuniordev e @brasizza Acredito que o correto seja realmente um 401 Unauthorized com um corpo:
> 
> ```json
> {
> "error": "refresh_token_not_yet_valid",
> "error_description": "The token cannote be used before [data/hora]"
> }
> ```
> 
> o que acham?

Eu gosto dessa abordagem , acho q fica facil  entendimento

**Comment by adilsonjuniordev** [comment]
@rodrigorahman acho uma ótima ideia, esse final de semana vou ter um tempinho livre, vou fazer esses ajustes e mandar para vocês darem uma olhada e ver o que acham ;)

**Comment by adilsonjuniordev** [comment]
> @adilsonjuniordev e @brasizza Acredito que o correto seja realmente um 401 Unauthorized com um corpo: 
> 
> ```json
> {
> "error": "refresh_token_not_yet_valid",
> "error_description": "The token cannote be used before [data/hora]"
> }
> ```
> 
> o que acham?

@rodrigorahman acho uma ótima ideia, esse final de semana vou ter um tempinho livre, vou fazer esses ajustes e mandar para vocês darem uma olhada e ver o que acham ;)

**Comment by rodrigorahman** [comment]
Correção disponivel na versão [3.2.1](https://pub.dev/packages/json_rest_server/versions/3.2.1)
