### ISSUE TITLE
Json Rest Server - Bad state: No element

### ISSUE THREAD

**Issue by catalunha** [rodrigorahman/json_rest_server#4]
Parabens @rodrigorahman e @brasizza 
Quando executei pela primeira vez o package me retorna:
`catalunha@pop-os:~/myapp/AcademiaDoFlutter/jornadagetx_scrollmixin/backend$ json_rest_server run
Json Rest Server Server started, responding on:
http://localhost:8080/
`
Então naturalmente eu clico no terminal e ele me leva a url informada.
![image](https://user-images.githubusercontent.com/19995819/193449771-d1b4e4da-ad18-4865-ab6c-bcd56342cd63.png)
E fornece esta saida:
`catalunha@pop-os:~/myapp/AcademiaDoFlutter/jornadagetx_scrollmixin/backend$ json_rest_server run
Json Rest Server Server started, responding on:
http://localhost:8080/
[ERROR] 2022-10-02 07:35:27.502626	0:00:00.004597	GET	/
Bad state: No element
dart:core                                                                      _Array.last
package:json_rest_server/src/core/middlewares/auth_middleware.dart 21:18       AuthMiddleware.execute
package:json_rest_server/src/core/middlewares/default_content_type.dart 12:40  DefaultContentType.execute

ERROR - 2022-10-02 07:35:27.605513
GET /
Error thrown by handler.
Bad state: No element
dart:core                                                                      _Array.last
package:json_rest_server/src/core/middlewares/auth_middleware.dart 21:18       AuthMiddleware.execute
package:json_rest_server/src/core/middlewares/default_content_type.dart 12:40  DefaultContentType.execute
`
Neste ponto deparei com as infos de erro e consultei a comunidade. 
Ocupando tempo desnecessario dos colegas. Ja peço desculpas.

Mas não era problema no package nem em minha instalação. Pois eu não informei uma url valida.

Então sugiro coloca no package, em caso sem url ou com url de pura '/' uma saida igual no NGINX que ele da um boas vindas. E instruções pedindo url com exemplo tipo:  http://localhost:8080/users

Pois como esta sem url e com '/' ele informa Internal Server Error. O que creio não ser verdade.

**Comment by brasizza** [comment]
#5 Mandei um PR! vamos ver se tá  de acordo e isso vai pra master!

**Comment by rodrigorahman** [comment]
release 1.2.3
