### ISSUE TITLE
RHEL, Fedora, and CentOS based distributions

### ISSUE THREAD

**Issue by apsantos-dev** [rodrigorahman/json_rest_server#8]
> Erro ao executar o comando: json_rest_server version

@rodrigorahman no Discord possui uma dúvida quanto ao executar o comando `json_rest_server version`. Acabei encontrando a solução editando o arquivo abaixo:

- [ ] #!/usr/bin/env sh
- [x] #!/usr/bin/env bash

```sh
file: ~/.pub-cache/bin/json_rest_server
```

---

Antes:

```sh
#!/usr/bin/env sh
# This file was created by pub v2.18.6.
# Package: json_rest_server
# Version: 1.3.1
# Executable: json_rest_server
# Script: json_rest_server
```

Agora:

```sh
#!/usr/bin/env bash
# This file was created by pub v2.18.6.
# Package: json_rest_server
# Version: 1.3.1
# Executable: json_rest_server
# Script: json_rest_server
```

---

Resolvi abrir essa issue caso alguém tenha este mesmo erro. Meu sistema operacional:

> Fedora Linux 37 (Workstation Edition)

---

Link da conversa: [https://discord.com/channels/754049391836397589/754049467979923519/1071420827360313384](https://discord.com/channels/754049391836397589/754049467979923519/1071420827360313384)

**Comment by rodrigorahman** [comment]
@apsantos-dev muito obrigado pela contribuição ;-)
